spring:
  application:
    name: index-config-server
  cloud:
    config:
      #      label 表示 分支：
      label: master
      server:
        git:
          #          uri 表示 git 地址：
          uri: https://github.com/xnxnxnxn/trendConfig/
          #          searchPaths 表示目录：
          searchPaths: config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/